# Judge v0.1 - services.yaml
# Author: Ryan Cobb (@cobbr_io)
# Project Home: https://github.com/cobbr/Judge
# License: GNU GPLv3

teams:
  # The team that should be scored based on the functionality of this service
  - team_name : Baylor
  - team_name : SMU

services:
  # Available service_types are: dns, http, https, ftp, mail
  - service_type_name       : dns
  # A name for this service, will be displayed on the scoreboard
    service_name            : Baylor DNS
  # The server IP that will be queried for this service
    service_connection      : 129.62.148.40
  # The domain name that this service is querying
    service_request         : baylor.edu
  - service_type_name       : http
    service_name            : CS HTTP
    service_connection      : cs.baylor.edu
    service_request         : /~donahoo/x.html
  - service_type_name       : https
    service_name            : DMZ HTTPS
    service_connection      : 172.25.21.11
    service_request         : /
  - service_type_name       : http
    service_name            : CS HTTP1
    service_connection      : cs.baylor.edu
    service_request         : /~donahoo/
  - service_type_name       : ftp
    service_name            : ftp baylor
    service_connection      : 127.0.0.1
    service_request         : None
  - service_type_name       : mail
    service_name            : mailtest
    service_connection      : 127.0.0.1
    service_request         : None

